final products = [
  {
    "id": "0",
    "title": "Men's Adidas Shoes",
    "price": 2999,
    "imageUrl": "assets/images/adidas_one.png",
    "company": "Adidas",
    "sizes": [8, 9, 10, 11],
  },
  {
    "id": "1",
    "title": "Men's Nike Shoes",
    "price": 3899,
    "imageUrl": "assets/images/nike_one.png",
    "company": "Nike",
    "sizes": [8, 9, 10, 11],
  },
  {
    "id": "2",
    "title": "Men's Adidas Shoes",
    "price": 2499,
    "imageUrl": "assets/images/adidas_two.png",
    "company": "Adidas",
    "sizes": [8, 9, 10, 11],
  },
  {
    "id": "3",
    "title": "Men's Nike Shoes",
    "price": 6999,
    "imageUrl": "assets/images/nike_two.png",
    "company": "Nike",
    "sizes": [8, 9, 10, 11],
  },
  {
    "id": "4",
    "title": "Men's Nike Shoes",
    "price": 1999,
    "imageUrl": "assets/images/nike_three.png",
    "company": "Nike",
    "sizes": [8, 9, 10, 11],
  },
];
